// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/proto/controlplane.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LastSeen      string                 `protobuf:"bytes,2,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_internal_proto_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_internal_proto_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *Node) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_internal_proto_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_internal_proto_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_internal_proto_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_internal_proto_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterNodeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_internal_proto_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_controlplane_proto_rawDescGZIP(), []int{4}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_internal_proto_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type SubmitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_internal_proto_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitTaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_internal_proto_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ClaimTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTaskRequest) Reset() {
	*x = ClaimTaskRequest{}
	mi := &file_internal_proto_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRequest) ProtoMessage() {}

func (x *ClaimTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRequest.ProtoReflect.Descriptor instead.
func (*ClaimTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimTaskRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type ClaimTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTaskResponse) Reset() {
	*x = ClaimTaskResponse{}
	mi := &file_internal_proto_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskResponse) ProtoMessage() {}

func (x *ClaimTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskResponse.ProtoReflect.Descriptor instead.
func (*ClaimTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *ClaimTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_internal_proto_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CompleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskResponse) Reset() {
	*x = CompleteTaskResponse{}
	mi := &file_internal_proto_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskResponse) ProtoMessage() {}

func (x *CompleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_controlplane_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteTaskResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_internal_proto_controlplane_proto protoreflect.FileDescriptor

const file_internal_proto_controlplane_proto_rawDesc = "" +
	"\n" +
	"!internal/proto/controlplane.proto\x12\fcontrolplane\"Q\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tlast_seen\x18\x02 \x01(\tR\blastSeen\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\"a\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\"%\n" +
	"\x13RegisterNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14RegisterNodeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x12\n" +
	"\x10ListNodesRequest\"=\n" +
	"\x11ListNodesResponse\x12(\n" +
	"\x05nodes\x18\x01 \x03(\v2\x12.controlplane.NodeR\x05nodes\"-\n" +
	"\x11SubmitTaskRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\"<\n" +
	"\x12SubmitTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.controlplane.TaskR\x04task\"&\n" +
	"\x10ClaimTaskRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\";\n" +
	"\x11ClaimTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.controlplane.TaskR\x04task\"%\n" +
	"\x13CompleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14CompleteTaskResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xa9\x03\n" +
	"\fControlPlane\x12U\n" +
	"\fRegisterNode\x12!.controlplane.RegisterNodeRequest\x1a\".controlplane.RegisterNodeResponse\x12L\n" +
	"\tListNodes\x12\x1e.controlplane.ListNodesRequest\x1a\x1f.controlplane.ListNodesResponse\x12O\n" +
	"\n" +
	"SubmitTask\x12\x1f.controlplane.SubmitTaskRequest\x1a .controlplane.SubmitTaskResponse\x12L\n" +
	"\tClaimTask\x12\x1e.controlplane.ClaimTaskRequest\x1a\x1f.controlplane.ClaimTaskResponse\x12U\n" +
	"\fCompleteTask\x12!.controlplane.CompleteTaskRequest\x1a\".controlplane.CompleteTaskResponseB!Z\x1fprometheus/internal/proto;protob\x06proto3"

var (
	file_internal_proto_controlplane_proto_rawDescOnce sync.Once
	file_internal_proto_controlplane_proto_rawDescData []byte
)

func file_internal_proto_controlplane_proto_rawDescGZIP() []byte {
	file_internal_proto_controlplane_proto_rawDescOnce.Do(func() {
		file_internal_proto_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_controlplane_proto_rawDesc), len(file_internal_proto_controlplane_proto_rawDesc)))
	})
	return file_internal_proto_controlplane_proto_rawDescData
}

var file_internal_proto_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_proto_controlplane_proto_goTypes = []any{
	(*Node)(nil),                 // 0: controlplane.Node
	(*Task)(nil),                 // 1: controlplane.Task
	(*RegisterNodeRequest)(nil),  // 2: controlplane.RegisterNodeRequest
	(*RegisterNodeResponse)(nil), // 3: controlplane.RegisterNodeResponse
	(*ListNodesRequest)(nil),     // 4: controlplane.ListNodesRequest
	(*ListNodesResponse)(nil),    // 5: controlplane.ListNodesResponse
	(*SubmitTaskRequest)(nil),    // 6: controlplane.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),   // 7: controlplane.SubmitTaskResponse
	(*ClaimTaskRequest)(nil),     // 8: controlplane.ClaimTaskRequest
	(*ClaimTaskResponse)(nil),    // 9: controlplane.ClaimTaskResponse
	(*CompleteTaskRequest)(nil),  // 10: controlplane.CompleteTaskRequest
	(*CompleteTaskResponse)(nil), // 11: controlplane.CompleteTaskResponse
}
var file_internal_proto_controlplane_proto_depIdxs = []int32{
	0,  // 0: controlplane.ListNodesResponse.nodes:type_name -> controlplane.Node
	1,  // 1: controlplane.SubmitTaskResponse.task:type_name -> controlplane.Task
	1,  // 2: controlplane.ClaimTaskResponse.task:type_name -> controlplane.Task
	2,  // 3: controlplane.ControlPlane.RegisterNode:input_type -> controlplane.RegisterNodeRequest
	4,  // 4: controlplane.ControlPlane.ListNodes:input_type -> controlplane.ListNodesRequest
	6,  // 5: controlplane.ControlPlane.SubmitTask:input_type -> controlplane.SubmitTaskRequest
	8,  // 6: controlplane.ControlPlane.ClaimTask:input_type -> controlplane.ClaimTaskRequest
	10, // 7: controlplane.ControlPlane.CompleteTask:input_type -> controlplane.CompleteTaskRequest
	3,  // 8: controlplane.ControlPlane.RegisterNode:output_type -> controlplane.RegisterNodeResponse
	5,  // 9: controlplane.ControlPlane.ListNodes:output_type -> controlplane.ListNodesResponse
	7,  // 10: controlplane.ControlPlane.SubmitTask:output_type -> controlplane.SubmitTaskResponse
	9,  // 11: controlplane.ControlPlane.ClaimTask:output_type -> controlplane.ClaimTaskResponse
	11, // 12: controlplane.ControlPlane.CompleteTask:output_type -> controlplane.CompleteTaskResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_controlplane_proto_init() }
func file_internal_proto_controlplane_proto_init() {
	if File_internal_proto_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_controlplane_proto_rawDesc), len(file_internal_proto_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_controlplane_proto_goTypes,
		DependencyIndexes: file_internal_proto_controlplane_proto_depIdxs,
		MessageInfos:      file_internal_proto_controlplane_proto_msgTypes,
	}.Build()
	File_internal_proto_controlplane_proto = out.File
	file_internal_proto_controlplane_proto_goTypes = nil
	file_internal_proto_controlplane_proto_depIdxs = nil
}
